In [5]:
import os
os.getcwd()

'c:\\Users\\Mikael Huff\\Documents\\Training\\Projects\\LEGO'

In [27]:
import pandas as pd
import numpy as np

In [12]:
os.listdir()
os.path.exists('Lego_Tracking\Train\Lego1\gt.txt')

True

In [25]:
gt = pd.read_csv('Lego_Tracking\Train\Lego1\gt.txt', header=None)
gt.head()

    0  1    2  3   4   5  6  7  8  9
0   7  0  454  1  43  16  1 -1 -1 -1
1   8  0  451  0  61  24  1 -1 -1 -1
2   9  0  448  0  66  28  1 -1 -1 -1
3  10  0  446  0  68  32  1 -1 -1 -1
4  11  0  446  0  70  41  1 -1 -1 -1

In [22]:
gt.describe()

,0,1,2,3,4,5,6,7,8,9
count,2220.000000,2220.0,2220.000000,2220.000000,2220.000000,2220.000000,2220.0,2220.0,2220.0,2220.0
mean,189.654955,0.0,488.457658,231.115766,264.248198,164.935586,1.0,-1.0,-1.0,-1.0
std,68.854772,0.0,187.181672,221.562031,117.230256,88.964986,0.0,0.0,0.0,0.0
min,7.000000,0.0,116.000000,0.000000,18.000000,9.000000,1.0,-1.0,-1.0,-1.0
25%,141.750000,0.0,370.250000,0.000000,164.000000,88.000000,1.0,-1.0,-1.0,-1.0
50%,199.000000,0.0,484.000000,181.000000,294.500000,160.000000,1.0,-1.0,-1.0,-1.0
75%,245.000000,0.0,580.000000,407.250000,376.000000,215.000000,1.0,-1.0,-1.0,-1.0
max,300.000000,0.0,950.000000,711.000000,413.000000,384.000000,1.0,-1.0,-1.0,-1.0

In [43]:
gt_np = gt.to_numpy()[:,2:6]
i=187
(gt_np/np.array([1280,720,1280,720]))[i:i+5]

array([[0.26484375, 0.08888889, 0.1484375 , 0.40416667],
       [0.33828125, 0.01111111, 0.3109375 , 0.26388889],
       [0.421875  , 0.        , 0.228125  , 0.20277778],
       [0.63828125, 0.        , 0.0609375 , 0.24305556],
       [0.11953125, 0.        , 0.18515625, 0.17361111]])

In [45]:
import cv2

In [73]:
import cv2
import os

def make_video(image_folder, output_video_name):
    # Define video parameters
    fps = 20
    fourcc = cv2.VideoWriter_fourcc(*'MP4V')  # Or 'MJPG' for .avi

    # Get and sort image files
    # print(image_folder)
    images = [img for img in os.listdir(image_folder) if img.endswith((".png", ".jpg", ".jpeg"))]
    # print(len(images))
    images.sort()

    # Get dimensions from the first image
    first_image_path = os.path.join(image_folder, images[0])
    frame = cv2.imread(first_image_path)
    height, width, layers = frame.shape
    frame_size = (width, height)

    # Initialize VideoWriter
    video_writer = cv2.VideoWriter(output_video_name, fourcc, fps, frame_size)

    # Write images to video
    for image_name in images:
        image_path = os.path.join(image_folder, image_name)
        frame = cv2.imread(image_path)
        video_writer.write(frame)

    # Release the VideoWriter
    video_writer.release()

    print(f"Video '{output_video_name}' created successfully!")

In [74]:
main_dir = os.path.join(os.getcwd(), 'Lego_Tracking\\Test\\')
output_dir = os.path.join(os.getcwd(), 'videos/')
# print('0',  os.getcwd())
# print('1', main_dir)
# print('2', output_dir)
if os.path.exists(output_dir) == False:
    os.mkdir(output_dir)
    
for dir_name in os.listdir(main_dir):
    print('3', dir_name)
    image_dir = os.path.join(main_dir,dir_name+'/img1/')
    # print('4', os.listdir(image_dir))
    make_video(image_dir, output_dir +dir_name + '-test.mp4')

3 Lego1
Video 'c:\Users\Mikael Huff\Documents\Training\Projects\LEGO\videos/Lego1-test.mp4' created successfully!
3 Lego2
Video 'c:\Users\Mikael Huff\Documents\Training\Projects\LEGO\videos/Lego2-test.mp4' created successfully!

In [75]:
os.getcwd()

'c:\\Users\\Mikael Huff\\Documents\\Training\\Projects\\LEGO'

In [ ]:
N = 100
np.arange(0, .2 * N, .2*N//10) +

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])