In [1]:
import pandas as pd

In [2]:
# testing_data = pd.read_csv('data/banking/new_test.csv')
data = pd.read_csv('data/banking/new_train.csv')
data.shape
# training_data.info()
# testing_data.head()

(32950, 16)

In [ ]:
data.select_dtypes(include=['object']).value_counts
data.describe(include=['object'])

,job,marital,education,default,housing,loan,contact,month,day_of_week,poutcome,y
count,32950,32950,32950,32950,32950,32950,32950,32950,32950,32950,32950
unique,12,4,8,3,3,3,2,10,5,3,2
top,admin.,married,university.degree,no,yes,no,cellular,may,thu,nonexistent,no
freq,8314,19953,9736,26007,17254,27131,20908,11011,6857,28416,29238

In [6]:
# testing_data.describe(include=['object'])
testing_data.head()
testing_data.describe()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,duration,campaign,poutcome
count,8238.000000,8238.000000,8238.000000,8238.000000,8238.000000,8238.000000,8238.000000,8238.000000,8238.000000,8238.000000,8238.000000,8238.000000,8238.000000
mean,39.613498,3.729425,1.170430,3.740592,0.201141,1.072833,0.320952,0.364409,4.220685,2.020879,227.820588,2.207575,0.932629
std,9.021371,3.597274,0.610371,2.134617,0.400878,0.985527,0.717918,0.481293,2.321464,1.386752,160.447506,1.380902,0.357648
min,26.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,36.000000,1.000000,0.000000
25%,32.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,3.000000,1.000000,101.000000,1.000000,1.000000
50%,38.000000,2.000000,1.000000,3.000000,0.000000,2.000000,0.000000,0.000000,4.000000,2.000000,178.000000,2.000000,1.000000
75%,47.000000,7.000000,2.000000,6.000000,0.000000,2.000000,0.000000,1.000000,6.000000,3.000000,319.000000,3.000000,1.000000
max,55.000000,11.000000,3.000000,7.000000,1.000000,2.000000,2.000000,1.000000,9.000000,4.000000,554.000000,5.000000,2.000000

In [ ]:
# testing_data.head()
data.head()
x_train = pd.get_dummies(data.drop(['y'], axis=1))
y_train = data['y']
x_test = pd.get_dummies(testing_data)
# x_train = pd.get_dummies(testing_data.drop(['y'], axis=1))
# y_test = testing_data['y']
testing_data.shape
# pd.get_dummies(testing_data).shape

(8238, 13)

In [45]:

from sklearn.metrics import classification_report, confusion_matrix

In [46]:
def perform_model(model_type):

    model_type.fit(x_train, y_train)
    y_pred = model_type.predict(x_test)

    return y_pred

In [47]:
from sklearn.neighbors import KNeighborsClassifier

In [48]:
perform_model(KNeighborsClassifier(n_neighbors=5))

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- contact
- day_of_week
- default
- education
- housing
- ...
Feature names seen at fit time, yet now missing:
- contact_cellular
- contact_telephone
- day_of_week_fri
- day_of_week_mon
- day_of_week_thu
- ...